%global maj_ver 18
%global min_ver 0
%global patch_ver 0
%undefine rc_ver

%global llvm_snapshot_version            18.0.0
%global llvm_snapshot_version_tag        18.0.0~pre20231225.ga041da31093303
%global llvm_snapshot_version_major      18
%global llvm_snapshot_version_minor      0
%global llvm_snapshot_version_patch      0
%global llvm_snapshot_yyyymmdd           20231225
%global llvm_snapshot_git_revision       a041da31093303b02b6da5fe919a0a3c234eb466
%global llvm_snapshot_git_revision_short a041da31093303
%global llvm_snapshot_version_suffix     pre20231225.ga041da31093303
%global llvm_snapshot_changelog_entry    * Mon Dec 25 2023 LLVM snapshot - 18.0.0~pre20231225.ga041da31093303
%global llvm_snapshot_source_prefix      https://github.com/kwk/llvm-daily-fedora-rpms/releases/download/source-snapshot/
